services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile-fastapi
    networks:
      - nginx-network
  nginx:
    depends_on:
      - fastapi
    build:
      context: .
      dockerfile: auto_round_robin
    ports:
      - "3336:80"
    networks:
      - nginx-network
networks:
  nginx-network:
    driver: bridge