services:
  fastapi1:
    build:
      context: .
      dockerfile: Dockerfile-fastapi
    networks:
      - nginx-network
  fastapi2:
    build:
      context: .
      dockerfile: Dockerfile-fastapi
    networks:
      - nginx-network
  fastapi3:
    build:
      context: .
      dockerfile: Dockerfile-fastapi
    networks:
      - nginx-network
  nginx:
    depends_on:
      - fastapi1
      - fastapi2
      - fastapi3
    build:
      context: .
      dockerfile: round_robbin
    ports:
      - "3336:80"
    networks:
      - nginx-network
networks:
  nginx-network:
    driver: bridge